NOOP = 0
LEFT = 1
RIGHT = 2
UP = 3
DOWN = 4
DO = 5
SLEEP = 6
PLACE_STONE = 7
PLACE_TABLE = 8
PLACE_FURNACE = 9
PLACE_PLANT = 10
MAKE_WOOD_PICKAXE = 11
MAKE_STONE_PICKAXE = 12
MAKE_IRON_PICKAXE = 13
MAKE_WOOD_SWORD = 14
MAKE_STONE_SWORD = 15
MAKE_IRON_SWORD = 16

action_translation_dict = {
    NOOP: "NOOP",
    LEFT: "LEFT",
    RIGHT: "RIGHT",
    UP: "UP",
    DOWN: "DOWN",
    DO: "DO",
    SLEEP: "SLEEP",
    PLACE_STONE: "PLACE_STONE",
    PLACE_TABLE: "PLACE_TABLE",
    PLACE_FURNACE: "PLACE_FURNACE",
    PLACE_PLANT: "PLACE_PLANT",
    MAKE_WOOD_PICKAXE: "MAKE_WOOD_PICKAXE",
    MAKE_STONE_PICKAXE: "MAKE_STONE_PICKAXE",
    MAKE_IRON_PICKAXE: "MAKE_IRON_PICKAXE",
    MAKE_WOOD_SWORD: "MAKE_WOOD_SWORD",
    MAKE_STONE_SWORD: "MAKE_STONE_SWORD",
    MAKE_IRON_SWORD: "MAKE_IRON_SWORD",
}